name: Security Baseline

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  secrets:
    name: Secrets Detection
    uses: hel-isa/security-gate/.github/workflows/reusable-secrets.yml@86e8ec53a459cf019013bb2297597cca575eae67
    with:
      fail_on_findings: true
